name: tutorial

on: 
    push:
        branches: 
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              uses: actions/checkout@v3
            - run: echo "hello!"
              shell: bash
    goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Goodbye World
              uses: actions/checkout@v3
            - run: echo "goodbye!"
              shell: bash
 

