# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Print the content of github object

on:
  issues:
    types: [opened]
    
jobs:
 comment-with-action:
   runs-on: ubuntu-latest
   steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github) }}' | jq
        shell: bash
